openapi: 3.0.0
info:
  title: Trip planner api
  version: 1.0.0

paths:
  /google/auth:
    post:
      operationId: googleAuth
      summary: Sign in/up with Google
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
                  description: id_token provided by Google
                client_type:
                  type: string
                  description: can be web or ios
            examples:
              example:
                value:
                  id_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                  client_type: web
      responses:
        200:
          description: |-
            OK. jwt tokens header can be decoded into [alg, exp, type]. jwt tokens payload can be decoded into [email, picture, name].
          content:
            application/json:
              examples:
                Sign in/up successfully:
                  value:
                      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOsIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjzxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJi_adQssw5c
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                invalid id_token:
                  value:
                      message: invalid id_token
                invalid client_type:
                  value:
                      message: invalid client_type
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: [missing fields]"

  /signin:
    post:
      operationId: passwordSigin
      summary: Sign in with password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: user email
                password:
                  type: string
                  description: user password
            examples:
              example:
                value:
                  email: willy3124@email.com
                  password: this is secure
      responses:
        200:
          description: |-
            OK. jwt tokens header can be decoded into [alg, exp, type]. jwt tokens payload can be decoded into [email, picture, name].
          content:
            application/json:
              examples:
                Sign in successfully:
                  value:
                      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOsIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjzxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJi_adQssw5c
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                User doesnt exist:
                  value:
                      message: user doesnt exist or password incorrect
                Password incorrect:
                  value:
                      message: user doesnt exist or password incorrect
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: {missing fields}"
  /signup:
    post:
      operationId: passwordSigin
      summary: Sign up with password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: user email
                password:
                  type: string
                  description: user password
                first_name:
                  type: string
                  description: user first name
                last_name:
                  type: string
                  description: user last name
            examples:
              example:
                value:
                  email: willy3124@email.com
                  password: this is secure
                  first_name: Willy
                  last_name: Lien
      responses:
        200:
          description: |-
            OK. jwt tokens header can be decoded into [alg, exp, type]. jwt tokens payload can be decoded into [email, picture, name].
          content:
            application/json:
              examples:
                Sign in successfully:
                  value:
                      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOsIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjzxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJi_adQssw5c
        409:
          description: |-
            Conflict.
          content:
            application/json:
              examples:
                email already used:
                  value:
                      message: email already used
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: {missing fields}"

  /test_auth:
    get:
      operationId: testAuth
      summary: Check whether current user is signed in
      security:
        - BearerAuth: []
      responses:
        200:
          description: |-
            OK.
          content:
            application/json:
              examples:
                User signed in:
                  value:
                      message: you are authorized
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                user not signed in:
                  value:
                      message: you are not authorized
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                missing header:
                  value:
                      message: "The following fields are missing in header: {missing_keys}"

  /plan/create:
    post:
      operationId: createPlan
      summary: Create plan
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: plan name
                date:
                  type: string
                  description: plan date in the format MM/DD/YY
            examples:
              example:
                value:
                  name: very fun plan
                  date: 06/15/2024
      responses:
        200:
          description: |-
            OK.
          content:
            application/json:
              examples:
                Plan created successfully:
                  value:
                    plan_id: 6688693729a03432a97f4180
                    name: very fun plan
                    date: 06/15/2024
                    owner: 66886919b80970c71c3d5f4b
                    members: [66886919b80970c71c3d5f4b]
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: {missing fields}"
                missing header:
                  value:
                      message: "The following fields are missing in header: {missing_keys}"
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                user not signed in:
                  value:
                      message: you are not signed in
  /plan/update:
    post:
      operationId: updatePlan
      summary: Update plan
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: string
                  description: plan id
                name:
                  type: string
                  description: plan name
                date:
                  type: string
                  description: plan date in the format MM/DD/YY
                owner:
                  type: string
                  description: owner id
                members:
                  type: array
                  items:
                    type: string
                  description: list of members' ids
                activities:
                  type: array
                  items:
                    type: string
                  description: list of activities' ids
            examples:
              example:
                value:
                  plan_id: 6688693729a03432a97f4180
                  name: very fun plan
                  date: 06/15/2024
                  owner: 66886919b80970c71c3d5f4b
                  members: [66886919b80970c71c3d5f4b]
                  activities: [6689ace820b661acd6743e71]
      responses:
        200:
          description: |-
            OK.
          content:
            application/json:
              examples:
                Plan updated successfully:
                  value:
                    plan_id: 6688693729a03432a97f4180
                    name: very fun plan
                    date: 06/15/2024
                    owner: 66886919b80970c71c3d5f4b
                    members: [66886919b80970c71c3d5f4b]
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: {missing fields}"
                missing header:
                  value:
                      message: "The following fields are missing in header: {missing_keys}"
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                user not signed in:
                  value:
                      message: you are not signed in
        403:
          description: |-
            Forbidden.
          content:
            application/json:
              examples:
                non-member trying to update plan:
                  value:
                      message: action is not permitted with the give user
                non-owner trying to update plan's ownership:
                  value:
                      message: action is not permitted with the give user

  /plan/delete:
    post:
      operationId: deletePlan
      summary: Delete plan
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: string
                  description: plan id
            examples:
              example:
                value:
                  plan_id: 6688693729a03432a97f4180
      responses:
        200:
          description: |-
            OK.
          content:
            application/json:
              examples:
                Plan deleted successfully:
                  value:
                    message: plan deleted
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: {missing fields}"
                missing header:
                  value:
                      message: "The following fields are missing in header: {missing_keys}"
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                user not signed in:
                  value:
                      message: you are not signed in
        403:
          description: |-
            Forbidden.
          content:
            application/json:
              examples:
                non-member trying to update plan:
                  value:
                      message: action is not permitted with the give user
                non-owner trying to update plan's ownership:
                  value:
                      message: action is not permitted with the give user

  /plan/get:
    get:
      operationId: getPlans
      summary: Get all plans the current user is part of
      security:
        - BearerAuth: []
      responses:
        200:
          description: |-
            OK.
          content:
            application/json:
              examples:
                User signed in:
                  value:
                    - plan_id: 6688693729a03432a97f4180
                      name: first plan
                      date: 06/15/2024
                      owner: 66886919b80970c71c3d5f4b
                      members: [66886919b80970c71c3d5f4b]
                    - plan_id: 6688693729a03432a97f4196
                      name: second plan
                      date: 06/16/2024
                      owner: 66886919b80970c71c3d5f4b
                      members: [66886919b80970c71c3d5f4b]
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                user not signed in:
                  value:
                      message: you are not authorized
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                missing header:
                  value:
                      message: "The following fields are missing in header: {missing_keys}"

  /activity/create:
    post:
      operationId: createActivity
      summary: Create activity
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: activity name
                plan_id:
                  type: string
                  description: plan id
                location:
                  type: string
                  description: location address
                start_time:
                  type: string
                  description: activity start_time in the format MM/DD/YY HH:MM:SS
                end_time:
                  type: string
                  description: activity end_time in the format MM/DD/YY HH:MM:SS
                note:
                  type: string
                  description: note address
            examples:
              example:
                value:
                  name: new activity
                  plan_id: 6689ab706be969d2b7f93fad
                  location: here
                  start_time: 09/19/22 13:55:26
                  end_time: 09/19/22 15:35:12
                  note: cool note
      responses:
        200:
          description: |-
            OK.
          content:
            application/json:
              examples:
                Activity created successfully:
                  value:
                    name: new activity
                    activity_id: 6689ace820b661acd6743e71
                    plan_id: 6689ab706be969d2b7f93fad
                    location: here
                    start_time: 09/19/22 13:55:26
                    end_time: 09/19/22 15:35:12
                    note: cool note
        400:
          description: |-
            Bad Request.
          content:
            application/json:
              examples:
                request body is invalid:
                  value:
                      message: request body is an invalid JSON
                request body missing required fields:
                  value:
                      message: "The following fields are missing in body: {missing fields}"
                missing header:
                  value:
                      message: "The following fields are missing in header: {missing_keys}"
        401:
          description: |-
            Unauthorized.
          content:
            application/json:
              examples:
                user not signed in:
                  value:
                      message: you are not signed in
