# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/pylint
    rev: v3.2.3
    hooks:
    -   id: pylint
        args: [ "--rcfile=backend/.pylintrc",]
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v1.3.3
    hooks:
    -   id: cfn-python-lint
        files: backend/template.yaml
