AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  back-end

  Sample SAM Template for back-end

Parameters:
  ApplicationName:
    Type: String
    Description: Name of our backend service
    Default: TripPlanner
  FirebaseProjectId:
    Type: String
    Default: trip-planner-1b0e0

Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: hello_world.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        HellowWorldAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi
            Path: /hello
            Method: GET

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: auth.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        AuthAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi
            Path: /auth
            Method: POST

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'CreateEventFunction'
      CodeUri: functions/
      Handler: create_event.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt CreateEventExecutionRole.Arn
      Events:
        CreateEventAPI:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi
            Path: /create_event
            Method: POST

  
  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: MyRestApi
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PATCH,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  CreateEventExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'CloudWatchLogPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/CreateEventFunction:*'

        - PolicyName: 'SecretsManagerAccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'secretsmanager:GetSecretValue'
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mongo-db-connection-secret-lzoiPy'

  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ApplicationName}'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
